version: 2

sources:
    - name: my_new_project
      description: This is a dbt project for managing CFA website data
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: web_data
      tables:
          - name: urldata
            description: Data scraped from CFA Websites